baseURL = 'http://example.org/'
languageCode = 'en-uk'
title = "CutThroat's Digital Garden"
theme = "shadocs"

[params]
  logo = "images/house-solid.svg"
  logoTouch = "images/house-solid.svg"
  favicon = "images/icon.png"
  toc = true
